### ISSUE TITLE
Couldn't install this Cvlib on Python 3.7.1 + pycharm + windows

### ISSUE THREAD

**Issue by SaddamBInSyed** [arunponnusamy/cvlib#22]
Hi there.

I am trying to run the CVLib and its examples code in pycharm and downloading the cvlib through  pip3.exe.
but I got struck while installing tensorflow.
error-
"could not find a version that satisfies the requirement tensorflow python 3.7"

could you please advise me regard this?

**Comment by arunponnusamy** [comment]
Hello @SaddamBInSyed , looks like Python 3.7 is not supported by TensorFlow on Windows yet. You might have to downgrade your python version. 
https://www.tensorflow.org/install/pip#package-location

**Comment by SaddamBInSyed** [comment]
Hi Arun,

As instructed I am using python 3.6 64bit ( windows) now, and I have installed the requirements.txt libs

but when I try to run the example then the below error occurred.

Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:\Users\saddam.h.SMARTV\Downloads\cvlib-master\cvlib-master\examples\face_detection_webcam.py 
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Users\saddam.h.SMARTV\Downloads\cvlib-master\cvlib-master\examples\face_detection_webcam.py", line 8, in <module>
    import cvlib as cv
  File "C:\Users\saddam.h.SMARTV\AppData\Local\Programs\Python\Python36\lib\site-packages\cvlib\__init__.py", line 8, in <module>
    from .gender_detection import detect_gender
  File "C:\Users\saddam.h.SMARTV\AppData\Local\Programs\Python\Python36\lib\site-packages\cvlib\gender_detection.py", line 4, in <module>
    from keras.utils import get_file
  File "C:\Users\saddam.h.SMARTV\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\saddam.h.SMARTV\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\saddam.h.SMARTV\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\saddam.h.SMARTV\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "C:\Users\saddam.h.SMARTV\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "C:\Users\saddam.h.SMARTV\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\saddam.h.SMARTV\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Users\saddam.h.SMARTV\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Users\saddam.h.SMARTV\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.
>>>

**Comment by SaddamBInSyed** [comment]
Hi arun,

After installing the Python 3.6.1 and tensorflow 1.13.1

now its working fine,

**Comment by SaddamBInSyed** [comment]
Hi Arun,

I could not download the gender_detection_model file.
please advise.

**Comment by arunponnusamy** [comment]
I have fixed this cache access issue just now. Yet to release the new package to PyPI. Meanwhile you can install it using `pip install git+https://github.com/arunponnusamy/cvlib.git`. Hopefully this should solve the issue for now.

**Comment by SaddamBInSyed** [comment]
Well noted with thanks.

can I have your contact details?
I am from near Chennai.
