### ISSUE TITLE
 module 'cvlib' has no attribute 'detect_face'

### ISSUE THREAD

**Issue by yensan0512** [arunponnusamy/cvlib#25]
C:\xampp\htdocs\faceD>python cvlib.py
Using TensorFlow backend.
WARNING:tensorflow:From C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-07-15 20:47:44.195976: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
WARNING:tensorflow:From C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Traceback (most recent call last):
  File "cvlib.py", line 12, in <module>
    import cvlib as cv
  File "C:\xampp\htdocs\faceD\cvlib.py", line 42, in <module>
    face, confidence = cv.detect_face(frame)
AttributeError: module 'cvlib' has no attribute 'detect_face'
[ WARN:0] terminating async callback

**Comment by arunponnusamy** [comment]
Hi @yensan0512 , can you try changing the name of the script you are running from `cvlib.py` to something else like `cvlib_script.py` ?

**Comment by yensan0512** [comment]
### I have change to cvlib_script.py but it still the same,sir

C:\xampp\htdocs\faceD>python cvlib_script.py
Using TensorFlow backend.
WARNING:tensorflow:From C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-07-16 14:37:08.106793: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
WARNING:tensorflow:From C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Traceback (most recent call last):
  File "cvlib_script.py", line 12, in <module>
    import cvlib_script as cv
  File "C:\xampp\htdocs\faceD\cvlib_script.py", line 42, in <module>
    face, confidence = cv.detect_face(frame)
AttributeError: module 'cvlib_script' has no attribute 'detect_face'

**Comment by arunponnusamy** [comment]
You can keep the import statement as 
```
import cvlib as cv
```
No need to change any code inside the script. The reason for changing the file name is it might confuse python while trying to import the package cvlib since the filename is also named cvlib.

**Comment by yensan0512** [comment]
It is okay, i get the output just the output will come out in two sqaure
label
